#:schema node_modules/wrangler/config-schema.json

name = "andrew-king-art-checker"
main = "source/index.ts"
compatibility_date = "2024-05-29"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["* * * * *"] # * * * * * = run every minute

[browser]
binding = "BROWSER"
