#:schema node_modules/wrangler/config-schema.json

name = "andrew-king-art-bot"
main = "source/art-bot.ts"
compatibility_date = "2024-05-29"

# Needed for the browser binding
compatibility_flags = ["nodejs_compat"]

# No HTTP access
workers_dev = false

[triggers]
# Run every 5 minutes
crons = ["*/5 * * * *"]

[browser]
binding = "BROWSER"

[[kv_namespaces]]
# Storing previously-seen paintings
id = "2f29821d5c524bbdb035720743d6f884"
binding = "ANDREW_KING_PAINTINGS"
